package com.taloarane.appcontroll.core

import androidx.compose.runtime.compositionLocalOf

data class L(
    val appName: String = "App Controll",
    val ram: String,
    val used: String,
    val totalRam: String,
    val userApps: String,
    val cache: String,
    val system: String,
    val free: String,
    val architecture: String,
    val ramType: String,
    val pageSize: String,
    val security: String,
    val clean: String,
    val cleanUser: String,
    val cleanSystem: String,
    val cleanCache: String,
    val filterActive: String,
    val filterAll: String,
    val filterInactive: String,
    val tabUser: String,
    val tabSystem: String,
    val tabWhitelist: String,
    val stop: String,
    val clear: String,
    val info: String,
    val uninstall: String,
    val whitelist: String,
    val infoRam: String,
    val infoRom: String,
    val infoSd: String,
    val settings: String,
    val language: String,
    val theme: String,
    val themeDark: String,
    val themeLight: String,
    val themeSystem: String,
    val keepScreenOn: String,
    val about: String,
    val on: String,
    val off: String,
    val warning: String,
    val danger: String,
    val warnSystemMsg: String,
    val dangerMsg: String,
    val cancel: String,
    val proceed: String,
    val holdToConfirm: String,
    val permissionsTitle: String,
    val permAccessibility: String,
    val permUsage: String,
    val permStorage: String,
    val permNotification: String,
    val permOverlay: String,
    val grant: String,
    val granted: String,
    val packageLabel: String,
    val uid: String,
    val sdk: String,
    val version: String,
    val lastUsed: String,
    val neverUsed: String,
    val apkSize: String,
    val installed: String,
    val close: String,
    val running: String,
    val stopped: String,
    val working: String,
    val done: String,
    val failed: String,
    val nothingToDo: String,
    val searchHint: String,
    val categories: String,
    val delete: String,
    val deleteConfirm: String,
    val empty: String,
    val estimated: String,
    val internalStorage: String,
    val sdCard: String,
    val sdCardMissing: String,
    val video: String,
    val images: String,
    val audio: String,
    val documents: String,
    val apks: String,
    val games: String,
    val apps: String,
    val systemFiles: String,
    val aboutText: String,
    val accessibilityNeeded: String,
)

val ID = L(
    ram = "RAM",
    used = "Terpakai",
    totalRam = "Total RAM",
    userApps = "APLIKASI USER",
    cache = "CACHE",
    system = "SISTEM",
    free = "BEBAS",
    architecture = "Arsitektur",
    ramType = "Tipe RAM",
    pageSize = "Page Size",
    security = "Keamanan",
    clean = "Bersihkan",
    cleanUser = "Pengguna",
    cleanSystem = "Sistem",
    cleanCache = "Cache",
    filterActive = "Aktif",
    filterAll = "Semua",
    filterInactive = "Non aktif",
    tabUser = "Pengguna",
    tabSystem = "Sistem",
    tabWhitelist = "Daftar Putih",
    stop = "Hentikan",
    clear = "Bersihkan",
    info = "Info",
    uninstall = "Uninstall",
    whitelist = "Daftar putih",
    infoRam = "Info RAM",
    infoRom = "Storage ROM",
    infoSd = "SD Card",
    settings = "Pengaturan",
    language = "Bahasa",
    theme = "Tema",
    themeDark = "Gelap",
    themeLight = "Terang",
    themeSystem = "Ikut sistem",
    keepScreenOn = "Layar tetap hidup",
    about = "Tentang aplikasi",
    on = "Hidupkan",
    off = "Matikan",
    warning = "Peringatan",
    danger = "BAHAYA",
    warnSystemMsg = "Ini adalah aplikasi sistem. Menghentikannya dapat membuat sebagian fungsi ponsel tidak stabil sampai perangkat dimulai ulang.",
    dangerMsg = "Aplikasi ini KRUSIAL bagi sistem (antarmuka, launcher, telepon, atau layanan inti). Menghentikannya bisa membuat layar hitam, ponsel tidak responsif, atau restart paksa.",
    cancel = "Batal",
    proceed = "Lanjutkan",
    holdToConfirm = "Tahan 2 detik untuk lanjut",
    permissionsTitle = "Izin yang diperlukan",
    permAccessibility = "Aksesibilitas (otomatisasi paksa berhenti)",
    permUsage = "Akses penggunaan (Usage Stats)",
    permStorage = "Kelola semua file (Storage)",
    permNotification = "Notifikasi progres",
    permOverlay = "Tampilkan di atas aplikasi lain",
    grant = "Berikan",
    granted = "Aktif",
    packageLabel = "Paket",
    uid = "UID",
    sdk = "SDK",
    version = "Versi",
    lastUsed = "Terakhir dipakai",
    neverUsed = "Belum pernah",
    apkSize = "Ukuran APK",
    installed = "Dipasang",
    close = "Tutup",
    running = "Aktif",
    stopped = "Non aktif",
    working = "Sedang memproses",
    done = "Selesai",
    failed = "Gagal",
    nothingToDo = "Tidak ada yang perlu diproses",
    searchHint = "Cari aplikasi",
    categories = "Kategori",
    delete = "Hapus",
    deleteConfirm = "Hapus berkas ini secara permanen?",
    empty = "Kosong",
    estimated = "estimasi",
    internalStorage = "Penyimpanan internal",
    sdCard = "Kartu SD",
    sdCardMissing = "Kartu SD tidak terpasang",
    video = "Video",
    images = "Gambar",
    audio = "Audio",
    documents = "Dokumen",
    apks = "APK / APKS",
    games = "Game",
    apps = "Aplikasi",
    systemFiles = "Sistem",
    aboutText = "App Controll membantu menghentikan aplikasi yang berjalan di latar, membersihkan cache, dan memantau RAM serta penyimpanan. Tanpa root, tanpa Shizuku — otomatisasi dilakukan lewat layanan aksesibilitas.",
    accessibilityNeeded = "Aktifkan layanan aksesibilitas App Controll terlebih dahulu.",
)

val EN = L(
    ram = "RAM",
    used = "Used",
    totalRam = "Total RAM",
    userApps = "USER APPS",
    cache = "CACHE",
    system = "SYSTEM",
    free = "FREE",
    architecture = "Architecture",
    ramType = "RAM type",
    pageSize = "Page size",
    security = "Security",
    clean = "Clean",
    cleanUser = "User",
    cleanSystem = "System",
    cleanCache = "Cache",
    filterActive = "Active",
    filterAll = "All",
    filterInactive = "Inactive",
    tabUser = "User",
    tabSystem = "System",
    tabWhitelist = "Whitelist",
    stop = "Stop",
    clear = "Clear",
    info = "Info",
    uninstall = "Uninstall",
    whitelist = "Whitelist",
    infoRam = "RAM info",
    infoRom = "Storage ROM",
    infoSd = "SD card",
    settings = "Settings",
    language = "Language",
    theme = "Theme",
    themeDark = "Dark",
    themeLight = "Light",
    themeSystem = "Follow system",
    keepScreenOn = "Keep screen on",
    about = "About",
    on = "On",
    off = "Off",
    warning = "Warning",
    danger = "DANGER",
    warnSystemMsg = "This is a system app. Stopping it may make some phone features unstable until you reboot.",
    dangerMsg = "This app is CRITICAL to the system (UI, launcher, phone or core services). Stopping it may cause a black screen, freeze, or forced restart.",
    cancel = "Cancel",
    proceed = "Proceed",
    holdToConfirm = "Hold 2 seconds to continue",
    permissionsTitle = "Required permissions",
    permAccessibility = "Accessibility (force stop automation)",
    permUsage = "Usage access (Usage Stats)",
    permStorage = "Manage all files (Storage)",
    permNotification = "Progress notifications",
    permOverlay = "Display over other apps",
    grant = "Grant",
    granted = "Granted",
    packageLabel = "Package",
    uid = "UID",
    sdk = "SDK",
    version = "Version",
    lastUsed = "Last used",
    neverUsed = "Never",
    apkSize = "APK size",
    installed = "Installed",
    close = "Close",
    running = "Active",
    stopped = "Inactive",
    working = "Working",
    done = "Done",
    failed = "Failed",
    nothingToDo = "Nothing to process",
    searchHint = "Search apps",
    categories = "Categories",
    delete = "Delete",
    deleteConfirm = "Permanently delete this file?",
    empty = "Empty",
    estimated = "estimate",
    internalStorage = "Internal storage",
    sdCard = "SD card",
    sdCardMissing = "No SD card detected",
    video = "Video",
    images = "Images",
    audio = "Audio",
    documents = "Documents",
    apks = "APK / APKS",
    games = "Games",
    apps = "Apps",
    systemFiles = "System",
    aboutText = "App Controll stops background apps, clears cache, and monitors RAM and storage. No root, no Shizuku — automation runs through the accessibility service.",
    accessibilityNeeded = "Enable the App Controll accessibility service first.",
)

val LocalL = compositionLocalOf { ID }
